<div id="propos">    
<p>FAQ projet XML</p>
    <p><b><a href="javascript:showHideData('data1', 'plusMinus1');"><span id="plusMinus1">[+]</span> A qui s'adresse ce site ?</a></b></p>
    <p id="data1" style="display: none;"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam facilisis metus enim, eget semper libero porta non. Morbi arcu dolor, ornare ut nulla a, condimentum vulputate velit. Integer lectus urna, tincidunt quis efficitur sit amet, tempus in ante. Phasellus vitae tortor non elit fringilla commodo. Suspendisse dui leo, congue eget euismod vel, malesuada nec felis. Phasellus non vestibulum ante, eu egestas libero. Sed mattis risus quis eros sollicitudin, et finibus ligula porttitor. Duis pretium facilisis sem, a volutpat arcu pretium quis. Proin risus sem, cursus at semper in, placerat porta tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus blandit nibh nisi, at luctus nunc bibendum in. Sed rutrum leo quis velit luctus, ut faucibus tortor laoreet. In pulvinar felis at lacus ornare, ac rutrum magna imperdiet. Cras vehicula lacus et condimentum cursus. Nunc feugiat pharetra cursus. Vestibulum felis sem, varius ac elit porta, vestibulum facilisis ex. </p>
<p><b><a href="javascript:showHideData('data2', 'plusMinus2');"><span id="plusMinus2">[+]</span> Que puis-je faire dessus ?</a></b></p>
    <p id="data2" style="display: none;"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam facilisis metus enim, eget semper libero porta non. Morbi arcu dolor, ornare ut nulla a, condimentum vulputate velit. Integer lectus urna, tincidunt quis efficitur sit amet, tempus in ante. Phasellus vitae tortor non elit fringilla commodo. Suspendisse dui leo, congue eget euismod vel, malesuada nec felis. Phasellus non vestibulum ante, eu egestas libero. Sed mattis risus quis eros sollicitudin, et finibus ligula porttitor. Duis pretium facilisis sem, a volutpat arcu pretium quis. Proin risus sem, cursus at semper in, placerat porta tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus blandit nibh nisi, at luctus nunc bibendum in. Sed rutrum leo quis velit luctus, ut faucibus tortor laoreet. In pulvinar felis at lacus ornare, ac rutrum magna imperdiet. Cras vehicula lacus et condimentum cursus. Nunc feugiat pharetra cursus. Vestibulum felis sem, varius ac elit porta, vestibulum facilisis ex. </p>
<p><b><a href="javascript:showHideData('data3', 'plusMinus3');"><span id="plusMinus3">[+]</span> Quelle est l'utilité de ce site et des informations qu'il contient ?</a></b></p>
    <p id="data3" style="display: none;"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam facilisis metus enim, eget semper libero porta non. Morbi arcu dolor, ornare ut nulla a, condimentum vulputate velit. Integer lectus urna, tincidunt quis efficitur sit amet, tempus in ante. Phasellus vitae tortor non elit fringilla commodo. Suspendisse dui leo, congue eget euismod vel, malesuada nec felis. Phasellus non vestibulum ante, eu egestas libero. Sed mattis risus quis eros sollicitudin, et finibus ligula porttitor. Duis pretium facilisis sem, a volutpat arcu pretium quis. Proin risus sem, cursus at semper in, placerat porta tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus blandit nibh nisi, at luctus nunc bibendum in. Sed rutrum leo quis velit luctus, ut faucibus tortor laoreet. In pulvinar felis at lacus ornare, ac rutrum magna imperdiet. Cras vehicula lacus et condimentum cursus. Nunc feugiat pharetra cursus. Vestibulum felis sem, varius ac elit porta, vestibulum facilisis ex. </p>
</div>
